version: '3.7'

services:
    ts-node-docker:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./src:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        container_name: home-pi-docker
        expose:
            - '8080'
            - '3000'
        ports:
            - '8080:8080'
            - '3000:3000'
        command: yarn dev
