version: '3.8'

services:
    home-pi-api:
        build:
            target: production
        command: node dist/index.js
    home-pi-ui:
        build:
            target: runner
        command: yarn start
